[No-Jira] Added a deafult PR template
toptal/keycodes pull request #324
Opened 2022-07-28 08:12 UTC by deniskaber

Added a deafult PR template

2022-07-28 13:11 UTC, filipechagas requested changes

2022-07-28 13:11 UTC, filipechagas commented on .github/pull_request_template.md
> +- [ ] Add acceptance criteria from Jira task [ABC-1234]
```suggestion
```

2022-07-28 13:11 UTC, filipechagas commented on .github/pull_request_template.md
> +[ABC-1234](https://toptal-core.atlassian.net/browse/ABC-1234)
```suggestion
# Title
```

2022-08-01 12:24 UTC, filipechagas approved these changes

2022-08-02 10:23 UTC, yusufzmly approved these changes

2022-08-03 08:28 UTC, merged