Update public repo with private repo code
toptal/keycodes pull request #326
Opened 2022-11-29 15:09 UTC by alexmcode

[UTI-2483](https://toptal-core.atlassian.net/browse/UTI-2483)

### Description

This PR will add into `keycodes-app` all progress from the private repo without sensitive info. Please check for that.

### How to test

- `yarn && yarn build && yarn start`
- check that everything is running properly - including tests

### Pre-merge checklist

- [x] The PR relates to a single subject with a clear title and description in grammatically correct, complete sentences.
- [x] Verify that feature branch is up-to-date with `main` (if not - rebase it).
- [x] Double-check the quality of [commit messages](http://chris.beams.io/posts/git-commit/).

2022-11-30 11:03 UTC, alexmcode commented on .github/pull_request_template.md
> +[ABC-1234](https://toptal-core.atlassian.net/browse/ABC-1234)
Hm.. so thinking about it I don't see any harm in having the task reference in the open source. As an advantage, I think it will be easier for us to track changes/commits across the repos. Maybe I'm not seeing something :) wdyt?

2022-11-30 11:09 UTC, alexmcode commented on .github/workflows/coverage.yml
> +  NPM_TOKEN: ${{ secrets.NPM_TOKEN_READ_ONLY }}
It seems that indeed we will not need this NPM_TOKEN reference as well. It's used for installing dependencies only. The question I have now is if this will generate too many conflicts on merge.. and if it's better to just leave them in as a compromise? wdyt?

2022-12-01 07:36 UTC, alexmcode commented
@toptal-anvil ping reviewers

2022-12-01 09:47 UTC, konstrybakov commented on .github/pull_request_template.md
> +[ABC-1234](https://toptal-core.atlassian.net/browse/ABC-1234)
I believe we shouldn't be using task references out in the open https://toptal-core.atlassian.net/wiki/spaces/UTI/pages/2713682133/Open-source+Projects+Maintenance+Guidelines#Public-Repository

2022-12-01 09:49 UTC, konstrybakov commented on .github/workflows/coverage.yml
> +  NPM_TOKEN: ${{ secrets.NPM_TOKEN_READ_ONLY }}
I don't think we should be leaving anything unneeded

2022-12-01 10:01 UTC, alexmcode commented on .github/workflows/coverage.yml
> +  NPM_TOKEN: ${{ secrets.NPM_TOKEN_READ_ONLY }}
got it. please check 0ec5a2c4f94324b2d248210a02b0414060457843

2022-12-01 10:01 UTC, alexmcode commented on .github/pull_request_template.md
> +[ABC-1234](https://toptal-core.atlassian.net/browse/ABC-1234)
got it. please check 0ec5a2c4f94324b2d248210a02b0414060457843

2022-12-01 10:07 UTC, yusufzmly commented on . eslintignore
> +public
EOL

2022-12-01 10:07 UTC, yusufzmly commented on .dockerignore
> +/.npmrc
We don't need /.npmrc here.

2022-12-01 10:08 UTC, yusufzmly commented on Dockerfile.deploy
> +COPY --chown=containeruser:containeruser deploying/.npmrc .
we don't need .npmrc here also

2022-12-01 10:08 UTC, yusufzmly commented on Dockerfile.deploy
> +COPY --chown=containeruser:containeruser deploying/.npmrc .
we don't need .npmrc here also

2022-12-01 10:08 UTC, yusufzmly commented on Dockerfile.deploy
> +COPY --chown=containeruser:containeruser deploying/.npmrc .
we don't need .npmrc here also

2022-12-01 10:09 UTC, yusufzmly commented on Dockerfile.deploy
> +COPY --chown=containeruser:containeruser deploying/.npmrc .
we don't need .npmrc here also

2022-12-01 10:27 UTC, alexmcode commented on Dockerfile.deploy
> +COPY --chown=containeruser:containeruser deploying/.npmrc .
thanks. done c809d8fb6cf3d53e18681efb0d2bf05167376ffc

2022-12-01 10:27 UTC, alexmcode commented on Dockerfile.deploy
> +COPY --chown=containeruser:containeruser deploying/.npmrc .
thanks. done c809d8fb6cf3d53e18681efb0d2bf05167376ffc

2022-12-01 10:27 UTC, alexmcode commented on Dockerfile.deploy
> +COPY --chown=containeruser:containeruser deploying/.npmrc .
thanks. done c809d8fb6cf3d53e18681efb0d2bf05167376ffc

2022-12-01 10:27 UTC, alexmcode commented on .dockerignore
> +/.npmrc
thanks. done c809d8fb6cf3d53e18681efb0d2bf05167376ffc

2022-12-01 10:27 UTC, alexmcode commented on . eslintignore
> +public
thanks. done c809d8fb6cf3d53e18681efb0d2bf05167376ffc

2022-12-01 12:52 UTC, konstrybakov requested changes
Hey Alex, 

Massive amount of work, thankyou! 

I left a few comments, but I also have some concerns which I am not sure we discussed.

Are we allowing running GH actions to everyone? How are they billed to us? If the WF time is billed the same for the public as for private, we need to limit the running of the actions to maintainers I believe. Also, Is happo free for the public? I can't remember for sure... So if WF is free, then have to make sure that Happo doesn't count toward the quota.

2022-12-01 12:52 UTC, konstrybakov commented on pages/api/healthcheck.ts
> +        'https://www.toptal.com/developers/gitignore'
[REQUEST]

This doesn't seem right :D

2022-12-01 12:52 UTC, konstrybakov commented on components/key-code-cards/basic-cards/EventKeyCard/index.test.tsx
> +  describe('correcly renders', () => {
```suggestion
  describe('correctly renders', () => {
```

2022-12-01 12:52 UTC, konstrybakov commented on config/sentry-filter.js
> + * Temporary fixes https://toptal-core.atlassian.net/browse/TG-1052
[CLEANUP]

A reference to toptal internals

2022-12-01 12:52 UTC, konstrybakov commented on docs/04-logging.md
> +# Logging
[CLEANUP]

Maybe rename this one to `03-logging'?

2022-12-01 13:16 UTC, alexmcode commented on .github/pull_request_template.md
> +
Right "Jira task" is not necessary but we will still have issues right (in GitHub probably?) So shouldn't we have the criteria here?

2022-12-01 13:25 UTC, alexmcode commented on LICENSE
> +Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, includi
it's not an md file so the formatting will not make any difference. Maybe I will put it on the same line to be more readable

2022-12-02 06:34 UTC, konstrybakov commented on .github/pull_request_template.md
> +
Sounds good to me! 👍

2022-12-02 06:35 UTC, konstrybakov commented on package.json
> +  "private": true,
So I guess we don't really need the `private: true`, no? Because we are not publishing it?

Either way, I don't mind leaving it as is

2022-12-02 06:36 UTC, konstrybakov approved these changes

2022-12-05 08:45 UTC, merged

2023-08-06 23:45 UTC, tavito commented
Hi @alexmcode! 

Regarding the "setIOSParameters" issue that was silenced on Sentry, do you have any information about the scenarios in which this error occurs? Could it potentially affect the users who receive the error?

Thank you in advance!

2023-08-07 06:01 UTC, alexmcode commented
Hey, @tavito I'm not sure I understand what problem are you referring to.
I also advise that if this is about an issue with Keycodes please open an issue to discuss it there since this is a closed PR. Thanks!

2023-08-07 21:54 UTC, tavito commented
Hey @alexmcode, thanks for your answer.

My question is about the file `config/sentry-filter.js` included in this PR, it has the following Sentry exclusion:

`'setIOSParameters', // Mobile Safari browser issue on iOS`

I just wondering if you remember if the error for that case could potentially affect the users who receive it. If you have decided to silence it, it is surely because it is harmless to the user, but I just want to confirm it.

Thank you!